data_path: ./nusax/datasets/mt

task: machine_translation
src_lang: indonesian
tgt_lang: english

model:  
  model: Seq2Seq
  src_emb_dim: 53
  tgt_emb_dim: 63
  encoder_hidden_dim: 128
  decoder_hidden_dim: 256
  num_layers: 4
  max_len: 200

train:
  epochs: 5
  batch_size: 32
  learning_rate: 0.001
  momentum: 0.99
  criterion: CrossEntropyLoss
  optimizer: Adam
  weight_decay: 0.01
  min_teacher_forcing_ratio: 0.2
  decay_rate: 0.02

output:
  checkpoint_path: ./checkpoints/test.pth
  plot_path: ./plots/test.png