data_path: ./nusax/datasets/mt

task: machine_translation
src_lang: indonesian
tgt_lang: english

model:  
  model: Seq2Seq
  src_emb_dim: 128
  tgt_emb_dim: 128
  encoder_hidden_dim: 256
  decoder_hidden_dim: 512
  num_layers: 2
  dropout_rate: 0.2
  max_len: 120

train:
  epochs: 20
  batch_size: 16
  learning_rate: 0.001
  momentum: 0.99
  criterion: CrossEntropyLoss
  optimizer: Adam
  weight_decay: 0.0001
  min_teacher_forcing_ratio: 0.8
  temperature: 1
  decay_rate: 0.01

output:
  checkpoint_path: ./checkpoints/test.pth
  plot_path: ./plots/test.png