data_path: ./nusax/datasets/mt

task: machine_translation
src_lang: indonesian
tgt_lang: english

model:  
  model: Seq2Seq
  src_emb_dim: 64
  tgt_emb_dim: 64
  encoder_hidden_dim: 128
  decoder_hidden_dim: 128
  num_encoder_layers: 4
  num_decoder_layers: 4
  max_len: 200
  teacher_forcing_ratio: 0.8

train:
  epochs: 2
  batch_size: 32
  learning_rate: 0.001
  momentum: 0.99
  criterion: CrossEntropyLoss
  optimizer: Adam

output:
  checkpoint_path: ./checkpoints/test.pth
  plot_path: ./plots/test.png